# Generated by Django 3.1.3 on 2020-11-26 20:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invests', '0002_auto_20201126_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='invest',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
